version: '3.8'
services:
  my-mysql-db:
    image: mysql:8.2
    container_name: db-events
    ports:
      - "3336:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 45645852
      MYSQL_DATABASE: wiselink-events
      MYSQL_USER: fran
      MYSQL_PASSWORD: 45645852
    volumes:
      - ./dbfiles:/docker-entrypoint-initdb.d
    networks:
      - backend
  my-go-app:
    container_name: back
    build:
      context: ./Back
    ports:
      - "8080:8080"
    networks:
      - backend
  front:
    container_name: front
    image: franbarrientos/eventos-wiselink-front
    ports:
      - "5175:80"
    depends_on:
      - my-go-app
    networks:
      - frontend
      - backend

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
networks:
  frontend:
  backend: